import sqlite3
from tkinter import * 
from tkinter import messagebox,ttk 
class Baza:
	def __init__(self):
		self.conn = sqlite3.connect('igre.sqlite') #'memory'
		self.curr = self.conn.cursor()
		self.definisanje_interfejsa()
		self.kreiranje_glavne_tabele()
		self.kreiranje_tabele_za_platforme()
		self.conn.commit()
		self.conn.close()
	def definisanje_interfejsa(self): 
		self.prozor = Tk()
		self.prozor.title("Baza podataka najboljih igrica ")
		self.prozor.geometry('400x330')
		self.prozor.resizable(False,False)
		self.ime_igrice = ttk.Label(self.prozor,text='Ime igrice : ')
		self.ime_igrice.grid(row=0,column=0,padx=10,pady=10,sticky=W)
		self.ime = ttk.Entry(self.prozor,width=42)
		self.ime.grid(row=0,column=0,padx=106,sticky=W)
		self.kompanija = ttk.Label(self.prozor,text="Ime kompanije : ")
		self.kompanija.grid(row=1,column=0,sticky=W,padx=10)
		self.unos_kompanije = ttk.Entry(self.prozor,width=41)
		self.unos_kompanije.grid(row=1,column=0,padx=110,sticky=W)
		self.godina = ttk.Label(self.prozor,text="Godina proizvodene igre : ")
		self.godina.grid(row=2,column=0,padx=10,sticky=W)
		self.unos_godine = ttk.Combobox(self.prozor)
		self.unos_godine['values']=[i+1 for i in range(2000,2022)]
		self.unos_godine.grid(row=2,column=0,sticky=W,padx=160,pady=10)
		self.unos_godine.current(0)
		self.btn_reset = ttk.Button(self.prozor,text="Reset",command=self.reset)
		self.btn_reset.grid(row=5,column=0,sticky=W,padx=30,pady=20)
		self.btn_sumbit = ttk.Button(self.prozor,text="Sumbit",command=self.sumbit)
		self.btn_sumbit.grid(row=5,column=0,sticky=W,padx=180,pady=20)
		self.zanr_lab = ttk.Label(self.prozor,text="Zanr igrice : ")
		self.zanr_lab.grid(row=3,column=0,sticky=W,padx=10)
		self.zanr = ttk.Combobox(self.prozor)
		self.zanr['values'] = ("Action","Advanture","Horror","Puzzle")
		self.zanr.grid(row=3,column=0,sticky=W,padx=100)
		self.zanr.current(0)
		self.platforma_id = ttk.Combobox(self.prozor)
		self.platforma_id['values']=(1,2,3,4)
		self.platforma_id.grid(row=4,column=0,padx=100,sticky=W)
		self.platforma_id.current(0)
		self.platforma = ttk.Label(self.prozor,text="ID platforme : ")
		self.platforma.grid(row=4,column=0,padx=10,pady=10,sticky=W)
		self.prikaz = ttk.Button(self.prozor,text='Prikaz',command=self.prikaz)
		self.prikaz.grid(row=5,padx=300)
		self.izmene()
		self.prozor.mainloop()
	def kreiranje_glavne_tabele(self):
		self.curr.execute("DROP TABLE IF EXISTS Igrice")
		self.curr.execute("Create Table Igrice (rbr INTEGER PRIMARY KEY AUTOINCREMENT,Naziv Text,Zanr Text,Kompanija Text,Godina Integer,id INTEGER,FOREIGN KEY(id) REFERENCES Platforma(id) )")
		self.curr.execute("INSERT INTO Igrice (Naziv,Zanr,Kompanija,Godina,id) VALUES('SHADOW','Akcija','Ubisoft',2015,1)" )
	def kreiranje_tabele_za_platforme(self):
		self.curr.execute("DROP TABLE if exists Platforma ")
		self.curr.execute("CREATE TABLE Platforma(id INTEGER PRIMARY KEY AUTOINCREMENT,platforma Text)")
		self.curr.execute("INSERT INTO  Platforma(platforma) VALUES('PC')")
		self.curr.execute("INSERT INTO  Platforma(platforma) VALUES('PS4')")
		self.curr.execute("INSERT INTO  Platforma(platforma) VALUES('PS5')")
		self.curr.execute("INSERT INTO  Platforma(platforma) VALUES('Andoid')")
		self.curr.execute("SELECT * FROM Platforma  ")
		self.curr.execute("SELECT * FROM Igrice INNER JOIN Platforma ON Platforma.id = Igrice.rbr")
	def sumbit(self):
		if self.ime.get() == "" or self.unos_kompanije.get() == "":
			 messagebox.showinfo(message='Niste uneli nista u polje')
		else:
			self.conn = sqlite3.connect('igre.sqlite')
			self.curr = self.conn.cursor()
			self.curr.execute('INSERT INTO Igrice(Naziv,Zanr,Kompanija,Godina,id) VALUES(:Naziv,:Zanr,:Kompanija,:Godina,:id)',{"Naziv":self.ime.get(),"Zanr":self.zanr.get(),'Kompanija':self.unos_kompanije.get(),'Godina':int(self.unos_godine.get()),'id':int(self.platforma_id.get())})
			self.conn.commit()
	def prikaz(self):
			self.novi_prozor = Tk()
			self.novi_prozor.title('Prikaz baze podataka')
			self.conn = sqlite3.connect('igre.sqlite')
			self.curr = self.conn.cursor()
			self.curr.execute("SELECT * FROM Igrice ")
			self.zapisi = self.curr.fetchall()
			print(self.zapisi)
			ispis_zapisa = ''
			for zapis in self.zapisi:
				self.prikaz=ttk.Label(self.novi_prozor,text=zapis)
				self.prikaz.grid(pady=15,sticky=W)
	def reset(self):
		self.ime.delete(0,END)
		self.unos_kompanije.delete(0,END)
	def izmene(self):
		self.lbl = ttk.Label(self.prozor,text='Izaberi id radi izmene : ',font=('Helveita',19))
		self.lbl.grid(row=6,sticky=W,column=0)
		self.combo = ttk.Combobox(self.prozor)
		self.combo['values']=(1,2,3,4)
		self.combo.current(0)
		self.id = self.combo.get()
		self.combo.grid(row=6,sticky=W,column=0,padx=260)

		self.brisanje = ttk.Button(self.prozor,text='Delete',command=self.brisanje)
		self.brisanje.grid(row=7,column=0,sticky=W,padx=250)
		self.edit = ttk.Button(self.prozor,text="Edit",command=self.editovanje)
		self.edit.grid(row=7,column=0,sticky=W,padx=100)	
	def nadogradnja(self):
		self.link = sqlite3.connect('igre.sqlite')
		self.curr = self.link.cursor()
		self.curr.execute('''UPDATE Igrice SET ime=:ime,unos_kompanije=:unos_kompanije,unos_godine=:unos_godine,zanr = :zanr,platforma_id=:platforma_id WHERE oid = :oid'''\
			,{'ime':self.ime2.get(),'unos_kompanije':self.unos_kompanije2.get(),'unos_godine':self.unos_godine2.get(),'zanr':self.zanr2.get(),'platforma_id':self.platforma_id2.get(),'oid':self.self.id})
		self.link.commit()
		self.link.close()
	def editovanje(self):
		self.prozor = Tk()
		self.prozor.geometry('400x250')
		self.prozor.resizable(False,False)
		self.link = sqlite3.connect('igre.sqlite')
		self.curr = self.link.cursor()
		self.curr.execute('SELECT * Igrice WHERE oid ' + self.id)
		self.zapisi = self.curr.fetchall()
		self.ime_drugo=ttk.Label(self.prozor,text='Ime igrice : ')
		self.ime_drugo.grid(row=0,column=0,padx=10,pady=10,sticky=W)
		self.ime2 = ttk.Entry(self.prozor,width=42)
		self.ime2.grid(row=0,column=0,padx=106,sticky=W)
		self.kompanija2 = ttk.Label(self.prozor,text="Ime kompanije : ")
		self.kompanija2.grid(row=1,column=0,sticky=W,padx=10)
		self.unos_kompanije2 = ttk.Entry(self.prozor,width=41)
		self.unos_kompanije2.grid(row=1,column=0,padx=110,sticky=W)
		self.godina2 = ttk.Label(self.prozor,text="Godina proizvodene igre : ")
		self.godina2.grid(row=2,column=0,padx=10,sticky=W)
		self.unos_godine2 = ttk.Combobox(self.prozor)
		self.unos_godine2['values']=[i+1 for i in range(2000,2022)]
		self.unos_godine2.grid(row=2,column=0,sticky=W,padx=160,pady=10)
		self.unos_godine2.current(0)
		self.btn_sumbit = ttk.Button(self.prozor,text="Sumbit",command=self.nadogradnja)
		self.btn_sumbit.grid(row=5,column=0,sticky=W,padx=180,pady=20)
		self.zanr_lab2 = ttk.Label(self.prozor,text="Zanr igrice : ")
		self.zanr_lab2.grid(row=3,column=0,sticky=W,padx=10)
		self.zanr2= ttk.Combobox(self.prozor)
		self.zanr2['values'] = ("Action","Advanture","Horror","Puzzle")
		self.zanr2.grid(row=3,column=0,sticky=W,padx=100)
		self.zanr2.current(0)
		self.platforma_id2 = ttk.Combobox(self.prozor)
		self.platforma_id2['values']=(1,2,3,4)
		self.platforma_id2.grid(row=4,column=0,padx=100,sticky=W)
		self.platforma_id2.current(0)
		self.platforma2 = ttk.Label(self.prozor,text="ID platforme : ")
		self.platforma2.grid(row=4,column=0,padx=10,pady=10,sticky=W)
		for zapis in self.zapisi:
			self.ime2.insert(0,zapis[0])
			self.unos_kompanije2.insert(0,zapis[1])
			self.unos_godine2.insert(0,zapis[2])
			self.zanr2.insert(0,zapis[3])
			self.platforma_id2.insert(0,insert[4])
		self.prozor.mainloop()
	def brisanje(self):
		self.link  = sqlite3.connect('igre.sqlite') 
		self.curr= self.link.cursor()
		self.curr.execute("DELETE from Igrice WHERE oid = " + self.combo.get())
		self.link.commit()
		self.link.close()
baza = Baza()
